services:
  app:
   build:
    context: .
    dockerfile: Dockerfile
   volumes:
     - ..:/workspace/vscode
   depends_on:
     - db

  db:
   image: postgres:latest
   restart: unless-stopped
   ports:
     - 5432:5432
   volumes:
     - postgres-data:/var/lib/postgresql-data
   environment:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: