apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
  namespace: monitoring
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
  type: LoadBalancer
